### ISSUE TITLE
how to save a history of previous input ?

### ISSUE THREAD

**Issue by mokun** [beryx/text-io#20]
Thanks to https://github.com/beryx/text-io/issues/17 that I now have the autocomplete setup for my program.

There are times that I would like to reenter the same input that I made in the past. 

Is there an elegant way to program the Left and Right arrow keys to scroll backward and forward the input ? 

I come up with this in `SwingHandler` but fall short of what to do next ?

```
    private static final String KEY_STROKE_LEFT = "pressed LEFT";
    private static final String KEY_STROKE_RIGHT = "pressed RIGHT";
    private String historyInput = "";
    private int historyIndex = -1;
    private String[] history = {};

  public SwingHandler(SwingTextTerminal terminal) {
        this.terminal = terminal;
        terminal.registerHandler(KEY_STROKE_LEFT, t -> {
            if (historyIndex >= 0) {
                historyIndex--;
                String text = (historyIndex < 0) ? historyInput : choices[historyIndex ];
                t.replaceInput(text, false);
            }
            return new ReadHandlerData(ReadInterruptionStrategy.Action.CONTINUE);
        });
```

**Comment by siordache** [comment]
You need a way to store and retrieve previously entered values. 
In [the demo app](https://github.com/beryx-gist/text-io-swing-handler) I implemented the [history store](https://github.com/beryx-gist/text-io-swing-handler/blob/master/src/main/java/org/beryx/swing/handler/History.java) using a properties file.
You may want to replace this solution with a more robust persistence mechanism.

I used Ctrl-Shift-Left and Ctrl-Shift-Right instead of just Left and Right, because I didn't want to disable the standard way to move the caret.

**Comment by mokun** [comment]
That's very awesome ! Using properties file to save the history will do the job well in my case.
