### ISSUE TITLE
Enhancement request: NullTerminal

### ISSUE THREAD

**Issue by tonypiazza** [beryx/text-io#9]
It would be useful for testing purposes to have a terminal type that just throws away all output. Similar to **/dev/null** in Unix/Linux world.

Thanks,

-Tony

**Comment by siordache** [comment]
I think the [MockTextTerminal](http://text-io.beryx.org/releases/latest/javadoc/org/beryx/textio/mock/MockTextTerminal.html) is what you need. It just stores the output in a string buffer, without actually printing anything.
It also lets you provide preconfigured values for the input in order to test read operations.
I use the MockTextTerminal to write Spock tests for text-io (see, for example, [TextIoSpec.groovy](https://github.com/beryx/text-io/blob/master/text-io/src/test/groovy/org/beryx/textio/TextIoSpec.groovy) and [TextIoReadSpec.groovy](https://github.com/beryx/text-io/blob/master/text-io/src/test/groovy/org/beryx/textio/TextIoReadSpec.groovy)).
